ARGS:
 # tab: 'pw3d_test'
 # eval_dataset: 'pw3d_test'

 tab: 'pw3d_test_pc'
 eval_dataset: 'pw3d_pc'

 # tab: 'pw3d_test_nc'
 # eval_dataset: 'pw3d_nc'

 # tab: 'pw3d_test_oc'
 # eval_dataset: 'pw3d_oc'
 
 GPUS: 0
 model_version: 1
 
 val_batch_size: 32
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: True

 
 # match_preds_to_gts_for_supervision: True
 # smpl_mesh_root_align: True

 backbone: 'resnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2
 model_precision: 'fp32'
 smpl_mesh_root_align: True

 model_path: /home/dcvl/MK/ROMP_Exp07_2/checkpoints/resnet_cm64_V1_resnet_on_gpu0,1_val/resnet_cm64_V1_resnet_epoch_7.pkl
 dataset_rootdir: '/home/dcvl/MK/ROMP/dataset' #'/path/to/dataset/3DPW'